sudo: false
language: node_js
node_js: "9"
install:
  - npm install
script:
  - npm run compile
  - npm run test
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
